- name: Get latest pcloud-cli release
  local_action:
    module: community.general.github_release
    user: saintedlama
    repo: pcloud-cli
    action: latest_release
  register: pcloud_gh

- name: Download pcloud-cli
  ansible.builtin.get_url:
    url: "https://github.com/saintedlama/pcloud-cli/releases/download/{{ pcloud_gh.tag }}/pcloud-cli_linux_amd64"
    dest: /usr/local/bin/pcloud-cli
    mode: '0755'
  become: true


