- name: Create backups bucket
  local_action:
    module: amazon.aws.s3_bucket
    access_key: "{{ s3_key }}"
    endpoint_url: "http://{{ inventory_hostname }}:9000"
    name: backups
    region: eu-west-1
    secret_key: "{{ s3_secret }}"
    state: present