- name: Create backups bucket
  local_action:
    module: amazon.aws.s3_bucket
    access_key: "{{ seaweed_key }}"
    endpoint_url: "http://{{ inventory_hostname }}:9000"
    name: backups
    region: eu-west-2
    secret_key: "{{ seaweed_secret }}"
    state: present