- name: Create service group
  ansible.builtin.group:
    name: "{{ svc_user }}"
    system: yes
    state: present
  become: true

- name: Create service user
  ansible.builtin.user:
    name: "{{ svc_user }}"
    group: "{{ svc_user }}"
    system: yes
    shell: /usr/sbin/nologin
    home: "{{ home_dir }}"
    create_home: yes
    state: present
  become: true