appendCommitMessageToRunName: false
name: "heartbeat_$(Date:yy.MM.dd).$(rev:rr)"
pr: none
trigger: none

schedules:
- cron: 0 19 * 1-3,11-12 * # 19:00 GMT (Nov-Mar)
  displayName: 19:00 GMT
  branches:
    include:
    - master
  always: true
- cron: 0 18 * 4-10 * # 19:00 BST (Apr-Oct)
  displayName: 19:00 BST
  branches:
    include:
    - master
  always: true

# These schedules will trigger at 7pm each day except:
# - the last days of March after the clocks go forward - will trigger at 8pm
# - the last days of October after the clocks go back - will trigger at 6pm
# minimum accuracy = 353/365 days, 96.7%

variables:
- group: ansible

pool:
  name: default
  demands:
  - Agent.Name -equals $(ansible_host)

jobs:
- job: test
  displayName: Test

  steps:
  - template: /.azuredevops/steps/whoami.yml
  - template: /.azuredevops/steps/inventory.yml