#!/usr/bin/env ansible-playbook

- name: Netbox DHCP Reservations
  hosts: rp04
  gather_facts: no
  ignore_unreachable: no

  # https://github.com/netbox-community/ansible_modules/blob/devel/plugins/lookup/nb_lookup.py

  vars:
    netbox_token: "{{ lookup('community.general.bitwarden_secrets_manager', '18b5879e-acf6-4c4b-8e12-b31c007cac94').value }}"
    local_file: netbox.conf
    output_file: /etc/dnsmasq.d/netbox.conf
  tasks:
  - name: Get Netbox data
    local_action:
      module: ansible.builtin.set_fact
      netbox_interfaces:     "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                             api_endpoint=netbox_endpoint,
                             validate_certs=false,
                             token=netbox_token) }}"
      netbox_ip_addresses:  "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                             api_endpoint=netbox_endpoint,
                             validate_certs=false,
                             token=netbox_token) }}"
      netbox_vm_interfaces: "{{ query('netbox.netbox.nb_lookup', 'virtualization-interfaces',
                             api_endpoint=netbox_endpoint,
                             validate_certs=false,
                             token=netbox_token) }}"
  - name: delete file
    local_action:
      module: ansible.builtin.file
      path: "{{ local_file }}"
      state: absent
  - name: append to file
    local_action: 
      module: ansible.builtin.lineinfile
      path: "{{ local_file }}"
      create: true
      state: present
      insertafter: EOF
      line: "dhcp-host={{ ( netbox_vm_interfaces | selectattr('key','eq',item.value.assigned_object.id) | map(attribute='value.mac_address') | first ) if item.value.assigned_object.virtual_machine is defined else ( netbox_interfaces | selectattr('key','eq',item.value.assigned_object.id) | map(attribute='value.mac_address') | first ) }},{{ item.value.address | split('/') | first }},{{ item.value.assigned_object.virtual_machine.display if item.value.assigned_object.virtual_machine is defined else item.value.assigned_object.device.display }}"
    with_items: "{{ netbox_ip_addresses }}"
    loop_control:
      label: "{{ item.value.address }}"
  - name: Copy to host
    ansible.builtin.copy:
      src: "{{ local_file }}"
      dest: "{{ output_file }}"
    become: true
    register: update_config
  - name: Restart pihole
    ansible.builtin.service:
      state: restarted
      name: pihole-FTL
    become: true
    when: update_config.changed is true