host_type: proxmox
proxmox_password: "{{ lookup('community.general.bitwarden_secrets_manager', 'ccd8e4f7-68f6-42d4-8677-b3a501005297').value }}"
proxmox_user: "{{ lookup('community.general.bitwarden_secrets_manager', '00118f7b-7078-4a05-aa25-b3a501004392').value }}"