- name: Install packages
  ansible.builtin.apt:
    pkg: "{{ pkg }}"
    state: "{{ headless_role_state }}"
    update_cache: yes
  become: true
  with_items: "{{ packages['debian'] }}"
  loop_control:
    loop_var: pkg

# TODO: run task install helper script
# TODO: run lazydocker install helper script
# TODO: run bw install script
