- name: Check architecture
  ansible.builtin.setup:
    filter:
      - 'architecture'
  when: ansible_architecture is undefined

- name: Create service group
  ansible.builtin.group:
    name: "{{ svc_user }}"
    system: yes
    state: present
  become: true

- name: Create service user
  ansible.builtin.user:
    name: "{{ svc_user }}"
    group: "{{ svc_user }}"
    groups:
    - kvm
    - netdev
    append: yes
    system: yes
    shell: /usr/sbin/nologin
    home: "{{ home_dir }}"
    create_home: yes
    state: present
  become: true

- name: Create automation group
  ansible.builtin.group:
    name: terraform
    system: yes
    state: present
  become: true

- name: Create automation user
  ansible.builtin.user:
    name: terraform
    group: terraform
    groups:
    - sudo
    append: yes
    system: yes
    shell: /bin/bash
    home: /opt/terraform
    create_home: yes
    state: present
    # password: TODO - secret, hashed 
  become: true

- name: Grant terraform access
  community.general.sudoers:
    name: terraform
    state: present
    user: terraform
    commands: ALL
    nopassword: true
  become: true

- name: Install dependencies
  ansible.builtin.package:
    name:
    - bridge-utils
    - iptables-persistent
    - cifs-utils 
    - samba 
    - smbclient
    state: present
  become: true

- name: Get latest release
  ansible.builtin.uri:
    url: https://api.github.com/repos/firecracker-microvm/firecracker/releases/latest
  register: github

- name: Download release
  ansible.builtin.unarchive:
    src: "https://github.com/firecracker-microvm/firecracker/releases/download/{{ github.json.tag_name }}/firecracker-{{ github.json.tag_name }}-{{ ansible_architecture }}.tgz"
    dest: /tmp
    remote_src: true
  become: true

- name: Install firecracker
  ansible.builtin.copy:
    src: "/tmp/release-{{ github.json.tag_name }}-{{ ansible_architecture }}/firecracker-{{ github.json.tag_name }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/firecracker
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Get network interfaces
  ansible.builtin.set_fact:
    primary_nic: "{{ interfaces | selectattr('name','eq','eth0') | map(attribute='description') | first }}"
    secondary_nic: "{{ interfaces | selectattr('name','eq','eth1') | map(attribute='description') | first }}"

- name: Configure network interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: "/etc/network/interfaces"
  become: true
  register: interfaces

- name: Configure iptables
  ansible.builtin.template:
    src: rules.v4.j2
    dest: "/etc/iptables/rules.v4"
  become: true
  register: iptables

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 3600
  become: true
  when: interfaces.changed is true or iptables.changed is true

- name: Create folders
  ansible.builtin.file:
    path: "{{ home_dir }}/{{ item }}"
    state: directory
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
  become: true
  with_items: "{{ shared_dirs }}"

- name: Deploy Samba Config
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  become: true
  register: samba_config

- name: Restart Samba
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: smbd
  become: true
  when: samba_config.changed is true