- name: Check architecture
  ansible.builtin.setup:
    filter:
      - 'architecture'
  when: ansible_architecture is undefined

- name: Create service group
  ansible.builtin.group:
    name: firecracker
    system: yes
    state: present
  become: true

- name: Create service user
  ansible.builtin.user:
    name: firecracker
    group: firecracker
    groups:
    - kvm
    append: yes
    system: yes
    shell: /usr/sbin/nologin
    home: /opt/firecracker
    create_home: yes
    state: present
  become: true

- name: Install dependencies
  ansible.builtin.package:
    name:
    - bridge-utils
    state: present
  become: true

- name: Get latest release
  ansible.builtin.uri:
    url: https://api.github.com/repos/firecracker-microvm/firecracker/releases/latest
  register: github

- name: Download release
  ansible.builtin.unarchive:
    src: "https://github.com/firecracker-microvm/firecracker/releases/download/{{ github.json.tag_name }}/firecracker-{{ github.json.tag_name }}-{{ ansible_architecture }}.tgz"
    dest: /tmp
    remote_src: true
  become: true

- name: Install firecracker
  ansible.builtin.copy:
    src: "/tmp/release-{{ github.json.tag_name }}-{{ ansible_architecture }}/firecracker-{{ github.json.tag_name }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/firecracker
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Get network interfaces
  ansible.builtin.set_fact:
    primary_nic: "{{ interfaces | selectattr('name','eq','eth0') | map(attribute='description') | first }}"
    secondary_nic: "{{ interfaces | selectattr('name','eq','eth1') | map(attribute='description') | first }}"

- name: Configure network interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: "/etc/network/interfaces"
  become: true
  register: interfaces

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 3600
  become: true
  when: interfaces.changed is true

- name: Create folders
  ansible.builtin.file:
    path: "/opt/firecracker/{{ item }}"
    state: directory
    owner: firecracker
    group: firecracker
  become: true
  with_items:
  - kernel
  - rootfs
  - vm

- name: Get Hello World kernel
  ansible.builtin.get_url:
    url: "https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin"
    dest: "/opt/firecracker/kernel/hello-vmlinux.bin"
    owner: firecracker
    group: firecracker
  become: true

- name: Get Hello World rootfs
  ansible.builtin.get_url:
    url: "https://s3.amazonaws.com/spec.ccfc.min/img/hello/fsfiles/hello-rootfs.ext4"
    dest: "/opt/firecracker/rootfs/hello-rootfs.ext4"
    owner: firecracker
    group: firecracker
  become: true

- name: Derive CI_VERSION (major.minor)
  ansible.builtin.set_fact:
    ci_version: "{{ github.json.tag_name | regex_replace('\\.[^.]+$', '') }}"

- name: Get available kernels
  ansible.builtin.uri:
    url: "http://spec.ccfc.min.s3.amazonaws.com/?prefix=firecracker-ci/{{ ci_version }}/{{ ansible_architecture }}/vmlinux-&list-type=2"
    return_content: yes
  register: kernel_list

- name: Get latest kernel
  set_fact:
    kernel_key: "{{ kernel_list.content | regex_findall('firecracker-ci/' + ci_version + '/' + ansible_architecture + '/vmlinux-[0-9]+\\.[0-9]+\\.[0-9]{1,3}')  | sort | last }}"

- name: Download kernel
  ansible.builtin.get_url:
    url: "https://s3.amazonaws.com/spec.ccfc.min/{{ kernel_key }}"
    dest: "/opt/firecracker/kernel/{{ kernel_key | split('/') | last  }}.bin"
    owner: firecracker
    group: firecracker
  become: true
