data_folder: /data
log_folder: /var/log/rustfs
s3_key: "{{ lookup('community.general.bitwarden_secrets_manager', '68e10816-aa77-4f58-9431-b457011d18d8').value }}"
s3_secret: "{{ lookup('community.general.bitwarden_secrets_manager', 'fb101f86-5a5d-4fd2-8667-b457011d2a58').value }}"
ssd_label: data
svc_user: rustfs
home_dir: "/opt/{{svc_user}}"
tape_count: 4
tape_folder: /mnt/tape
usb_folder: /mnt/rescue
usb_label: rescue
