- name: Install packages
  ansible.builtin.package:
    name:
    - awscli
    - samba
    - tar
    - transmission-daemon
    state: latest
  become: true

- name: Mount point 
  ansible.builtin.file:
    path: "{{ storage_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: "0777"
    state: directory
  become: true

- name: Mount storage
  ansible.posix.mount:
    path: "{{ storage_path }}"
    src: "LABEL={{ storage_label }}"
    fstype: ext4
    opts: "defaults,nofail"
    state: mounted
  become: true

- name: Storage folders
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: "0777"
    state: directory
  become: true
  with_items:
  - "{{ storage_path }}/downloads"
  - "{{ storage_path }}/incomplete"

- name: SMB config
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: '0644'
  become: true
  register: update_smb

- name: SMB Service
  ansible.builtin.service:
    state: restarted
    name: samba
  become: true
  when: update_smb.changed is true

- name: Stop Transmission service
  ansible.builtin.service:
    state: stopped
    name: transmission-daemon
  become: true

- name: Transmission settings
  ansible.builtin.copy:
    src: settings.json
    dest: /etc/transmission-daemon/settings.json
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0600'
  become: true

- name: Start Transmission service
  ansible.builtin.service:
    state: started
    name: transmission-daemon
  become: true

- name: Backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: "{{ storage_path }}/backup.sh"
    owner: root
    group: root
    mode: '0744'
  become: true


- name: Backup job      
  ansible.builtin.cron:
    name: backup-transmission
    minute: 20
    hour: 21
    weekday: SUN
    job: "{{ storage_path }}/backup.sh"
    user: root
  become: true