- name: Install packages (State = {{ kubernetes_role_state }})
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ pkg }}"
    state: "{{ kubernetes_role_state }}"
  become: true
  with_items: "{{ packages.wsus }}"
  loop_control:
    loop_var: pkg