- name: Install required pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pips['all'] + pips[patching] }}"
  loop_control:
    loop_var: item
  become: true
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"