- name: Install dependencies
  ansible.builtin.package:
    name:
    - wget
    state: present
  become: true

- name: Check if Docker installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: st

- name: Install Docker
  ansible.builtin.shell:
    cmd: wget -O - https://get.docker.com | bash
  become: true
  when: st.stat.exists is false

- name: create docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: add users to docker group
  ansible.builtin.user:
    name: '{{ user_name }}'
    groups: docker
    append: yes
  register: user_to_group
  become: true
  with_items: "{{ docker_users }}"
  loop_control:
    loop_var: user_name

- name: enable docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  
- ansible.builtin.reboot:
    reboot_timeout: 3600
  when: user_to_group.changed
  become: true